name: Pre-Commit

on:
  pull_request:
  push:
    branches: [main, develop]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v3
      with:
        python-version: '3.x'
    - name: Check if cache directory exists
      run: mkdir -p ~/.cache/pre-commit
    - name: Debug cache state
      run: ls -la ~/.cache/pre-commit
    - uses: pre-commit/action@v3.0.0
      with:
        extra_args: --all-files
